language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

install:
  - "pip install tabulate"
  - "pip install coveralls"
  - "pip install coverage"
  - "python -m build"

script:
   - coverage run --source raccoon -m py.test
   - coverage report -m

after_success:
  - coveralls
