language: python
matrix:
    include:
      - python: "3.8"
      - python: "3.9"
      - python: "3.10"
  
install:
  - "pip install blist"
  - "pip install tabulate"
  - "pip install coveralls"
  - "pip install coverage"
  - "python setup.py install"

script:
   - coverage run --source raccoon -m py.test
   - coverage report -m

after_success:
  - coveralls
